# Projet_DA

In [3]:
import pandas as pd, seaborn as sb

In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/q-pi/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [4]:
df = pd.read_csv("data/owid-covid-data.csv")
df2 = pd.read_csv("data/EDU_DEM_12092020154828100.csv")

In [5]:
df.query("location == \"France\"").fillna(0).query('total_cases != 0')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
13922,FRA,Europe,France,2020-01-25,3.0,3.0,0.429,0.0,0.0,0.000,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
13923,FRA,Europe,France,2020-01-26,3.0,0.0,0.429,0.0,0.0,0.000,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
13924,FRA,Europe,France,2020-01-27,3.0,0.0,0.429,0.0,0.0,0.000,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
13925,FRA,Europe,France,2020-01-28,3.0,0.0,0.429,0.0,0.0,0.000,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
13926,FRA,Europe,France,2020-01-29,4.0,1.0,0.571,0.0,0.0,0.000,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14149,FRA,Europe,France,2020-09-08,328980.0,4203.0,6850.714,30726.0,25.0,13.000,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
14150,FRA,Europe,France,2020-09-09,335524.0,6544.0,7073.857,30764.0,38.0,14.714,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
14151,FRA,Europe,France,2020-09-10,344101.0,8577.0,7296.714,30794.0,30.0,15.429,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
14152,FRA,Europe,France,2020-09-11,353944.0,9843.0,7680.429,30813.0,19.0,18.143,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901
14153,FRA,Europe,France,2020-09-12,363350.0,9406.0,7742.000,30893.0,80.0,29.571,...,38605.671,0.0,86.06,4.77,30.1,35.6,0.0,5.98,82.66,0.901

In [6]:
df2.query("YEAR == 2018 & SEX == \"T\" & AGE == \"T\"")[['Country', 'Value']]

              Country        Value
9           Australia   24992747.0
39            Austria    8822267.0
69            Belgium   11398589.0
99             Canada   36963854.0
129    Czech Republic   10610055.0
159           Denmark    5781190.0
189           Finland    5513130.0
219            France   66918941.0
249           Germany   82792351.0
279            Greece   10741165.0
309           Hungary    9778371.0
339           Iceland     348450.0
369           Ireland    4830392.0
399             Italy   60483973.0
429             Japan  126706210.0
459             Korea   51606633.0
489        Luxembourg     602005.0
519            Mexico  123364284.0
549       Netherlands   17181084.0
579       New Zealand    4885500.0
609            Norway    5295619.0
639            Poland   37976687.0
669          Portugal   10291027.0
699   Slovak Republic    5443120.0
729             Spain   46658447.0
759            Sweden   10120242.0
789       Switzerland    8484130.0
819            Turkey   80810525.0
849    United Kingdom   66273576.0
879     United States  325732103.0
909            Brazil  207651621.0
939             Chile   18751405.0
969          Colombia   49834240.0
999        Costa Rica    5003403.0
1029          Estonia    1319133.0
1059           Israel    8797940.0
1089           Latvia    1934379.0
1119        Lithuania    2808901.0
1149           Russia  146880432.0
1179         Slovenia    2066880.0

In [ ]:
merged = df.merge(df2, left_on='location', right_on='Country', how='left')